// src/components/svelte/Clock.svelte
<script lang="ts">
    import { onMount } from "svelte";

    let time = $state(new Date());

    const formatter = new Intl.DateTimeFormat("zh", {
        day: "numeric",
        month: "short",
        hour: "2-digit",
        minute: "2-digit",
        hour12: false,
    });

    onMount(() => {
        const intervalId = window.setInterval(() => {
            time = new Date();
        }, 1000);

        return () => window.clearInterval(intervalId);
    });
</script>

<span> {formatter.format(time)}</span>

// src/components/react/Clock.tsx
import { useEffect, useState } from "react";

export default function Clock() {
    const [time, setTime] = useState(new Date())
    useEffect(() => {
        const intervalId = setInterval(() => {
            setTime(new Date())
        }, 1000)
        return () => clearInterval(intervalId)
    }, [])

    return <span> {time.toLocaleTimeString(undefined, { day: "numeric", month: "short", hour: "2-digit", minute: "2-digit", hour12: true })}</span>
}
